# Generated by Django 6.0 on 2025-12-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
