# Generated by Django 6.0 on 2025-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Father_name', models.CharField(max_length=100)),
                ('Mother_name', models.CharField(max_length=100)),
                ('Roll', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Technology', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
